{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 40,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<table style=\"border: 2px solid white;\">\n",
       "<tr>\n",
       "<td style=\"vertical-align: top; border: 0px solid white\">\n",
       "<h3>Client</h3>\n",
       "<ul>\n",
       "  <li><b>Scheduler: </b>tcp://127.0.0.1:40627\n",
       "  <li><b>Dashboard: </b><a href='http://127.0.0.1:41213' target='_blank'>http://127.0.0.1:41213</a>\n",
       "</ul>\n",
       "</td>\n",
       "<td style=\"vertical-align: top; border: 0px solid white\">\n",
       "<h3>Cluster</h3>\n",
       "<ul>\n",
       "  <li><b>Workers: </b>8</li>\n",
       "  <li><b>Cores: </b>16</li>\n",
       "  <li><b>Memory: </b>32.00 GB</li>\n",
       "</ul>\n",
       "</td>\n",
       "</tr>\n",
       "</table>"
      ],
      "text/plain": [
       "<Client: scheduler='tcp://127.0.0.1:40627' processes=8 cores=16>"
      ]
     },
     "execution_count": 40,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "from dask.distributed import Client, progress\n",
    "client = Client(n_workers=8, threads_per_worker=2, memory_limit='4GB')\n",
    "client"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "\n",
    "import dask.dataframe as dd\n",
    "\n",
    "from TargetEncoderv3 import TargetEncoder\n",
    "from FeatureSelector import FeatureSelector\n",
    "\n",
    "from sklearn.metrics import *\n",
    "from sklearn.model_selection import *\n",
    "\n",
    "import lightgbm as lgb"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div><strong>Dask DataFrame Structure:</strong></div>\n",
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>ip</th>\n",
       "      <th>app</th>\n",
       "      <th>device</th>\n",
       "      <th>os</th>\n",
       "      <th>channel</th>\n",
       "      <th>click_time</th>\n",
       "      <th>attributed_time</th>\n",
       "      <th>is_attributed</th>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>npartitions=1</th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th></th>\n",
       "      <td>uint32</td>\n",
       "      <td>uint16</td>\n",
       "      <td>uint16</td>\n",
       "      <td>uint16</td>\n",
       "      <td>uint16</td>\n",
       "      <td>object</td>\n",
       "      <td>object</td>\n",
       "      <td>uint8</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th></th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>\n",
       "<div>Dask Name: from-delayed, 3 tasks</div>"
      ],
      "text/plain": [
       "Dask DataFrame Structure:\n",
       "                   ip     app  device      os channel click_time attributed_time is_attributed\n",
       "npartitions=1                                                                                 \n",
       "               uint32  uint16  uint16  uint16  uint16     object          object         uint8\n",
       "                  ...     ...     ...     ...     ...        ...             ...           ...\n",
       "Dask Name: from-delayed, 3 tasks"
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "dtypes = {\n",
    "            'ip'            : 'uint32',\n",
    "            'app'           : 'uint16',\n",
    "            'device'        : 'uint16',\n",
    "            'os'            : 'uint16',\n",
    "            'channel'       : 'uint16',\n",
    "            'is_attributed' : 'uint8',\n",
    "            'click_id'      : 'uint32'\n",
    "            }\n",
    "train = dd.read_csv(\"../input/train_sample.csv\", dtype=dtypes, blocksize=15000000,)\n",
    "train"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>ip</th>\n",
       "      <th>app</th>\n",
       "      <th>device</th>\n",
       "      <th>os</th>\n",
       "      <th>channel</th>\n",
       "      <th>click_time</th>\n",
       "      <th>attributed_time</th>\n",
       "      <th>is_attributed</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>87540</td>\n",
       "      <td>12</td>\n",
       "      <td>1</td>\n",
       "      <td>13</td>\n",
       "      <td>497</td>\n",
       "      <td>2017-11-07 09:30:38</td>\n",
       "      <td>NaN</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>105560</td>\n",
       "      <td>25</td>\n",
       "      <td>1</td>\n",
       "      <td>17</td>\n",
       "      <td>259</td>\n",
       "      <td>2017-11-07 13:40:27</td>\n",
       "      <td>NaN</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>101424</td>\n",
       "      <td>12</td>\n",
       "      <td>1</td>\n",
       "      <td>19</td>\n",
       "      <td>212</td>\n",
       "      <td>2017-11-07 18:05:24</td>\n",
       "      <td>NaN</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>94584</td>\n",
       "      <td>13</td>\n",
       "      <td>1</td>\n",
       "      <td>13</td>\n",
       "      <td>477</td>\n",
       "      <td>2017-11-07 04:58:08</td>\n",
       "      <td>NaN</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>68413</td>\n",
       "      <td>12</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>178</td>\n",
       "      <td>2017-11-09 09:00:09</td>\n",
       "      <td>NaN</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "       ip  app  device  os  channel           click_time attributed_time  \\\n",
       "0   87540   12       1  13      497  2017-11-07 09:30:38             NaN   \n",
       "1  105560   25       1  17      259  2017-11-07 13:40:27             NaN   \n",
       "2  101424   12       1  19      212  2017-11-07 18:05:24             NaN   \n",
       "3   94584   13       1  13      477  2017-11-07 04:58:08             NaN   \n",
       "4   68413   12       1   1      178  2017-11-09 09:00:09             NaN   \n",
       "\n",
       "   is_attributed  \n",
       "0              0  \n",
       "1              0  \n",
       "2              0  \n",
       "3              0  \n",
       "4              0  "
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "train.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 64,
   "metadata": {},
   "outputs": [],
   "source": [
    "def eval_fold(train, tr_index, val_index, cols, target_col, colname='new_col', func='mean', func_kwargs = {}):\n",
    "    X_tr = train.map_partitions(lambda x: x.iloc[tr_index, :], meta=train)\n",
    "    X_val = train.map_partitions(lambda x: x.iloc[val_index, :], meta=train)\n",
    "    #display(X_tr.head())\n",
    "\n",
    "    tmp = getattr(X_tr.groupby(cols)[target_col], func)(**func_kwargs)\n",
    "    tmp.name = colname\n",
    "    #display(tmp)\n",
    "    new_df = X_val.join(tmp.to_frame(), on=cols, how='left')[colname]\n",
    "    #display(new_df.head())\n",
    "    return new_df\n",
    "\n",
    "def cross_val_predict_dask(X, cvlist, cols, target_col, colname, func='mean', func_kwargs={}, verbose=1):\n",
    "    X_vals = []\n",
    "    for i, (tr_index, val_index) in enumerate(cvlist):\n",
    "        if verbose:\n",
    "            print(\"Working on fold {}\".format(i))\n",
    "        #print(X_tr.shape)\n",
    "        new_df = eval_fold(X, tr_index, val_index, cols=cols, target_col=target_col, colname=colname, func=func, func_kwargs=func_kwargs)\n",
    "        X_vals.append(new_df)\n",
    "    res = dd.concat(X_vals, axis=0)\n",
    "    print(res)\n",
    "    return res\n",
    "        \n",
    "        \n",
    "def cvFeatureGeneration(df, cvlist=None, cols=None, targetcol='is_attributed', func='mean', cname=None, func_kwargs={}):\n",
    "    target_df = cross_val_predict_dask(df,  cvlist, cols, targetcol, cname, func, func_kwargs, verbose=1)\n",
    "    df = df.join(target_df.to_frame())\n",
    "    return df\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 65,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Working on fold 0\n",
      "Working on fold 1\n",
      "Working on fold 2\n",
      "Working on fold 3\n",
      "Working on fold 4\n",
      "Working on fold 5\n",
      "Working on fold 6\n",
      "Working on fold 7\n",
      "Working on fold 8\n",
      "Working on fold 9\n",
      "Dask Series Structure:\n",
      "npartitions=10\n",
      "    float64\n",
      "        ...\n",
      "     ...   \n",
      "        ...\n",
      "        ...\n",
      "Name: device_mean, dtype: float64\n",
      "Dask Name: concat, 123 tasks\n"
     ]
    }
   ],
   "source": [
    "CVFOLDS = list(KFold(10).split(train, train.is_attributed))\n",
    "train = cvFeatureGeneration(train, cvlist=CVFOLDS, cols=['device'], targetcol='is_attributed', func='mean', cname='device_mean')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 66,
   "metadata": {},
   "outputs": [],
   "source": [
    "train = train.compute()\n",
    "train = dd.from_pandas(train, npartitions=1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 67,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Working on fold 0\n",
      "Working on fold 1\n",
      "Working on fold 2\n",
      "Working on fold 3\n",
      "Working on fold 4\n",
      "Working on fold 5\n",
      "Working on fold 6\n",
      "Working on fold 7\n",
      "Working on fold 8\n",
      "Working on fold 9\n",
      "Dask Series Structure:\n",
      "npartitions=10\n",
      "    float64\n",
      "        ...\n",
      "     ...   \n",
      "        ...\n",
      "        ...\n",
      "Name: os_mean, dtype: float64\n",
      "Dask Name: concat, 121 tasks\n"
     ]
    }
   ],
   "source": [
    "#CVFOLDS = list(KFold(10).split(train, train.is_attributed))\n",
    "train = cvFeatureGeneration(train, cvlist=CVFOLDS, cols=['os'], targetcol='is_attributed', func='mean', cname='os_mean')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 68,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>ip</th>\n",
       "      <th>app</th>\n",
       "      <th>device</th>\n",
       "      <th>os</th>\n",
       "      <th>channel</th>\n",
       "      <th>click_time</th>\n",
       "      <th>attributed_time</th>\n",
       "      <th>is_attributed</th>\n",
       "      <th>device_mean</th>\n",
       "      <th>os_mean</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>87540</td>\n",
       "      <td>12</td>\n",
       "      <td>1</td>\n",
       "      <td>13</td>\n",
       "      <td>497</td>\n",
       "      <td>2017-11-07 09:30:38</td>\n",
       "      <td>NaN</td>\n",
       "      <td>0</td>\n",
       "      <td>0.001484</td>\n",
       "      <td>0.001310</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>105560</td>\n",
       "      <td>25</td>\n",
       "      <td>1</td>\n",
       "      <td>17</td>\n",
       "      <td>259</td>\n",
       "      <td>2017-11-07 13:40:27</td>\n",
       "      <td>NaN</td>\n",
       "      <td>0</td>\n",
       "      <td>0.001484</td>\n",
       "      <td>0.001064</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>101424</td>\n",
       "      <td>12</td>\n",
       "      <td>1</td>\n",
       "      <td>19</td>\n",
       "      <td>212</td>\n",
       "      <td>2017-11-07 18:05:24</td>\n",
       "      <td>NaN</td>\n",
       "      <td>0</td>\n",
       "      <td>0.001484</td>\n",
       "      <td>0.001672</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>94584</td>\n",
       "      <td>13</td>\n",
       "      <td>1</td>\n",
       "      <td>13</td>\n",
       "      <td>477</td>\n",
       "      <td>2017-11-07 04:58:08</td>\n",
       "      <td>NaN</td>\n",
       "      <td>0</td>\n",
       "      <td>0.001484</td>\n",
       "      <td>0.001310</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>68413</td>\n",
       "      <td>12</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>178</td>\n",
       "      <td>2017-11-09 09:00:09</td>\n",
       "      <td>NaN</td>\n",
       "      <td>0</td>\n",
       "      <td>0.001484</td>\n",
       "      <td>0.000941</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "       ip  app  device  os  channel           click_time attributed_time  \\\n",
       "0   87540   12       1  13      497  2017-11-07 09:30:38             NaN   \n",
       "1  105560   25       1  17      259  2017-11-07 13:40:27             NaN   \n",
       "2  101424   12       1  19      212  2017-11-07 18:05:24             NaN   \n",
       "3   94584   13       1  13      477  2017-11-07 04:58:08             NaN   \n",
       "4   68413   12       1   1      178  2017-11-09 09:00:09             NaN   \n",
       "\n",
       "   is_attributed  device_mean   os_mean  \n",
       "0              0     0.001484  0.001310  \n",
       "1              0     0.001484  0.001064  \n",
       "2              0     0.001484  0.001672  \n",
       "3              0     0.001484  0.001310  \n",
       "4              0     0.001484  0.000941  "
      ]
     },
     "execution_count": 68,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "train = train.compute()\n",
    "train = dd.from_pandas(train, npartitions=5)\n",
    "train.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 69,
   "metadata": {},
   "outputs": [],
   "source": [
    "def eval_train(train, test, cols, target_col, colname='new_col', func='mean', func_kwargs = {}):\n",
    "    tmp = getattr(train.groupby(cols)[target_col], func)(**func_kwargs)\n",
    "    tmp.name = colname\n",
    "    #display(tmp)\n",
    "    new_df = test.join(tmp.to_frame(), on=cols, how='left')[colname]\n",
    "    #display(new_df.head())\n",
    "    return new_df\n",
    "    \n",
    "\n",
    "def testFeatureGeneration(train, test, cols=None, targetcol='is_attributed', func='mean', cname=None, func_kwargs={}):\n",
    "    target_df = eval_train(train, test, cols, targetcol, cname, func, func_kwargs)\n",
    "    test = test.join(target_df.to_frame())\n",
    "    return test"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 70,
   "metadata": {},
   "outputs": [],
   "source": [
    "test = dd.read_csv(\"../input/test.csv\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 71,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe11a2331d0> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe11a233e48> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe1199f0400> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe1199f0438> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe1199f0390> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe1199f0be0> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe1199f0da0> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe1199f09b0> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe119c36b00> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe119c360b8> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe119c36438> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe119c36278> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe119c36a20> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe119c36860> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe119c36630> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe119c36550> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe119c36400> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe1199c39b0> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe1199c38d0> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe1184d2b00> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe1184d2f60> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe1184d26d8> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe1184d22e8> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe1184d27f0> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe1184d20b8> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe1184d2e80> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe1184d2940> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe1184d2630> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe11852f8d0> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe11852fcc0> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe11852f630> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe11852fd68> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe11ae93c50> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe11ae93fd0> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe11ae93978> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe11ae93be0> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe11ae93828> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe1203fee10> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe1203fe908> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe120436eb8> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe1204366a0> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe120436cf8> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe11b42d7f0> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe11b42de48> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe11b8b8208> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe11b8b80f0> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe11b8b8ba8> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe11b8b8400> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe11b8b8860> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe11b8b8a58> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe11b8b8358> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe11b8b8160> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe117c8da58> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe117c8dd30> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe117c8db38> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe117c8db70> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe117c8d128> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe117c8d9b0> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe11b771c88> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe117a142b0> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe117a14dd8> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe117a14b00> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe117a147b8> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe11a1ade48> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe11a1addd8> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe11a1adf28> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe117c9a320> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe117c9a470> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe117c9a4a8> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe117c9a9b0> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe11a19e518> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe11a19ec50> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe11a19e8d0> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe11a19e860> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe11a19ea20> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe11a19e9b0> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe11a19e550> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe11a19e208> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe117a32470> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe117a325f8> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe11853c160> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe11853c128> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe11853c3c8> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe118533f60> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe1185336d8> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe118533630> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe118533cc0> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe118533ac8> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe12284dc88> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe1217737f0> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe121773a90> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe1217738d0> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe12058ed30> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe11850c7f0> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe11850c828> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe11850cb38> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe11850c160> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe11850c390> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe11850cf98> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe0d8be9da0> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe0d8be9550> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe0fc3cc5f8> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe0fc3cc0f0> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe0d9177668> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe0d9318240> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe0d9318be0> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe0d9318cf8> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe0d9318c50> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe0d9318828> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe0d9318e48> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe0d931d630> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe0d931d9b0> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe0d931dd68> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe0d931d208> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe0d931d2b0> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe0d903d748> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe0d903dc50> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe0d903d240> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe0d903de10> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe0d903dd68> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe0d903d8d0> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe0d903df28> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe0d903d160> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe0d903da90> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe117ef1668> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe117ef1fd0> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe0d8bd57f0> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe0d8bd5be0> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe0d8bd5438> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe0d903e550> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe0d903e2e8> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe0fc4746d8> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe0fc478940> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe0fc478518> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe0fc475400> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe0fc475828> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe0fc475320> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe0fc3d8160> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe0d9050d68> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe0fc3dd2b0> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe0fc3dd470> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe0d9320240> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe0d8bf2d30> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe0d8bf26a0> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe0d8bf2550> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe0d8bf24e0> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe0d8bf2470> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe0d8bf2278> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n"
     ]
    },
    {
     "ename": "KilledWorker",
     "evalue": "(\"('hash-join-09d35817760a39b681085d1ef906c8ea', 0)\", 'tcp://127.0.0.1:43043')",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mKilledWorker\u001b[0m                              Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-71-f08ef2dfa51c>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0mtest\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mtestFeatureGeneration\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mtrain\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mtest\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mcols\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m'device'\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mtargetcol\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m'is_attributed'\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mfunc\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m'mean'\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mcname\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m'device_mean'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 2\u001b[0;31m \u001b[0mtest\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mhead\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;32m~/anaconda3/lib/python3.6/site-packages/dask/dataframe/core.py\u001b[0m in \u001b[0;36mhead\u001b[0;34m(self, n, npartitions, compute)\u001b[0m\n\u001b[1;32m    844\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    845\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mcompute\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 846\u001b[0;31m             \u001b[0mresult\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mresult\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mcompute\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    847\u001b[0m         \u001b[0;32mreturn\u001b[0m \u001b[0mresult\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    848\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/lib/python3.6/site-packages/dask/base.py\u001b[0m in \u001b[0;36mcompute\u001b[0;34m(self, **kwargs)\u001b[0m\n\u001b[1;32m    133\u001b[0m         \u001b[0mdask\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mbase\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mcompute\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    134\u001b[0m         \"\"\"\n\u001b[0;32m--> 135\u001b[0;31m         \u001b[0;34m(\u001b[0m\u001b[0mresult\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mcompute\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mtraverse\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;32mFalse\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    136\u001b[0m         \u001b[0;32mreturn\u001b[0m \u001b[0mresult\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    137\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/lib/python3.6/site-packages/dask/base.py\u001b[0m in \u001b[0;36mcompute\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m    331\u001b[0m     postcomputes = [a.__dask_postcompute__() if is_dask_collection(a)\n\u001b[1;32m    332\u001b[0m                     else (None, a) for a in args]\n\u001b[0;32m--> 333\u001b[0;31m     \u001b[0mresults\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mget\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mdsk\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mkeys\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    334\u001b[0m     \u001b[0mresults_iter\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0miter\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mresults\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    335\u001b[0m     return tuple(a if f is None else f(next(results_iter), *a)\n",
      "\u001b[0;32m~/anaconda3/lib/python3.6/site-packages/distributed/client.py\u001b[0m in \u001b[0;36mget\u001b[0;34m(self, dsk, keys, restrictions, loose_restrictions, resources, sync, asynchronous, **kwargs)\u001b[0m\n\u001b[1;32m   1997\u001b[0m                 \u001b[0msecede\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1998\u001b[0m             \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1999\u001b[0;31m                 \u001b[0mresults\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mgather\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mpacked\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0masynchronous\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0masynchronous\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   2000\u001b[0m             \u001b[0;32mfinally\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   2001\u001b[0m                 \u001b[0;32mfor\u001b[0m \u001b[0mf\u001b[0m \u001b[0;32min\u001b[0m \u001b[0mfutures\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mvalues\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/lib/python3.6/site-packages/distributed/client.py\u001b[0m in \u001b[0;36mgather\u001b[0;34m(self, futures, errors, maxsize, direct, asynchronous)\u001b[0m\n\u001b[1;32m   1435\u001b[0m             return self.sync(self._gather, futures, errors=errors,\n\u001b[1;32m   1436\u001b[0m                              \u001b[0mdirect\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mdirect\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mlocal_worker\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mlocal_worker\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1437\u001b[0;31m                              asynchronous=asynchronous)\n\u001b[0m\u001b[1;32m   1438\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1439\u001b[0m     \u001b[0;34m@\u001b[0m\u001b[0mgen\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mcoroutine\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/lib/python3.6/site-packages/distributed/client.py\u001b[0m in \u001b[0;36msync\u001b[0;34m(self, func, *args, **kwargs)\u001b[0m\n\u001b[1;32m    590\u001b[0m             \u001b[0;32mreturn\u001b[0m \u001b[0mfuture\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    591\u001b[0m         \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 592\u001b[0;31m             \u001b[0;32mreturn\u001b[0m \u001b[0msync\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mloop\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mfunc\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m*\u001b[0m\u001b[0margs\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    593\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    594\u001b[0m     \u001b[0;32mdef\u001b[0m \u001b[0m__repr__\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/lib/python3.6/site-packages/distributed/utils.py\u001b[0m in \u001b[0;36msync\u001b[0;34m(loop, func, *args, **kwargs)\u001b[0m\n\u001b[1;32m    252\u001b[0m             \u001b[0me\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mwait\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;36m1000000\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    253\u001b[0m     \u001b[0;32mif\u001b[0m \u001b[0merror\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;36m0\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 254\u001b[0;31m         \u001b[0msix\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mreraise\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m*\u001b[0m\u001b[0merror\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;36m0\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    255\u001b[0m     \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    256\u001b[0m         \u001b[0;32mreturn\u001b[0m \u001b[0mresult\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;36m0\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/lib/python3.6/site-packages/six.py\u001b[0m in \u001b[0;36mreraise\u001b[0;34m(tp, value, tb)\u001b[0m\n\u001b[1;32m    691\u001b[0m             \u001b[0;32mif\u001b[0m \u001b[0mvalue\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m__traceback__\u001b[0m \u001b[0;32mis\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0mtb\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    692\u001b[0m                 \u001b[0;32mraise\u001b[0m \u001b[0mvalue\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mwith_traceback\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mtb\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 693\u001b[0;31m             \u001b[0;32mraise\u001b[0m \u001b[0mvalue\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    694\u001b[0m         \u001b[0;32mfinally\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    695\u001b[0m             \u001b[0mvalue\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/lib/python3.6/site-packages/distributed/utils.py\u001b[0m in \u001b[0;36mf\u001b[0;34m()\u001b[0m\n\u001b[1;32m    236\u001b[0m             \u001b[0;32myield\u001b[0m \u001b[0mgen\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mmoment\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    237\u001b[0m             \u001b[0mthread_state\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0masynchronous\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;32mTrue\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 238\u001b[0;31m             \u001b[0mresult\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;36m0\u001b[0m\u001b[0;34m]\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;32myield\u001b[0m \u001b[0mmake_coro\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    239\u001b[0m         \u001b[0;32mexcept\u001b[0m \u001b[0mException\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0mexc\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    240\u001b[0m             \u001b[0mlogger\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mexception\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mexc\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/lib/python3.6/site-packages/tornado/gen.py\u001b[0m in \u001b[0;36mrun\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m   1053\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1054\u001b[0m                     \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1055\u001b[0;31m                         \u001b[0mvalue\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mfuture\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mresult\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1056\u001b[0m                     \u001b[0;32mexcept\u001b[0m \u001b[0mException\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1057\u001b[0m                         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mhad_exception\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;32mTrue\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/lib/python3.6/site-packages/tornado/concurrent.py\u001b[0m in \u001b[0;36mresult\u001b[0;34m(self, timeout)\u001b[0m\n\u001b[1;32m    236\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_exc_info\u001b[0m \u001b[0;32mis\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    237\u001b[0m             \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 238\u001b[0;31m                 \u001b[0mraise_exc_info\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_exc_info\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    239\u001b[0m             \u001b[0;32mfinally\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    240\u001b[0m                 \u001b[0mself\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/lib/python3.6/site-packages/tornado/util.py\u001b[0m in \u001b[0;36mraise_exc_info\u001b[0;34m(exc_info)\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/lib/python3.6/site-packages/tornado/gen.py\u001b[0m in \u001b[0;36mrun\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m   1061\u001b[0m                     \u001b[0;32mif\u001b[0m \u001b[0mexc_info\u001b[0m \u001b[0;32mis\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1062\u001b[0m                         \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1063\u001b[0;31m                             \u001b[0myielded\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mgen\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mthrow\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m*\u001b[0m\u001b[0mexc_info\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1064\u001b[0m                         \u001b[0;32mfinally\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1065\u001b[0m                             \u001b[0;31m# Break up a reference to itself\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/lib/python3.6/site-packages/distributed/client.py\u001b[0m in \u001b[0;36m_gather\u001b[0;34m(self, futures, errors, direct, local_worker)\u001b[0m\n\u001b[1;32m   1313\u001b[0m                             six.reraise(type(exception),\n\u001b[1;32m   1314\u001b[0m                                         \u001b[0mexception\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1315\u001b[0;31m                                         traceback)\n\u001b[0m\u001b[1;32m   1316\u001b[0m                     \u001b[0;32mif\u001b[0m \u001b[0merrors\u001b[0m \u001b[0;34m==\u001b[0m \u001b[0;34m'skip'\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1317\u001b[0m                         \u001b[0mbad_keys\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0madd\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mkey\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/lib/python3.6/site-packages/six.py\u001b[0m in \u001b[0;36mreraise\u001b[0;34m(tp, value, tb)\u001b[0m\n\u001b[1;32m    691\u001b[0m             \u001b[0;32mif\u001b[0m \u001b[0mvalue\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m__traceback__\u001b[0m \u001b[0;32mis\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0mtb\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    692\u001b[0m                 \u001b[0;32mraise\u001b[0m \u001b[0mvalue\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mwith_traceback\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mtb\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 693\u001b[0;31m             \u001b[0;32mraise\u001b[0m \u001b[0mvalue\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    694\u001b[0m         \u001b[0;32mfinally\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    695\u001b[0m             \u001b[0mvalue\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mKilledWorker\u001b[0m: (\"('hash-join-09d35817760a39b681085d1ef906c8ea', 0)\", 'tcp://127.0.0.1:43043')"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe0fc7b8a58> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe0fc7b8908> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe0fc7b87b8> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe0fc7b8668> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe0fc7b8518> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe0fc7b83c8> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe0fc7b8278> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe0fc7b8128> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe11432bf98> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe11432be48> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe11432bcf8> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe11432bba8> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe11432ba58> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe11432b908> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe11432b7b8> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe11432b668> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe11432b518> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe11432b3c8> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe11432b278> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe11432b128> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe11430cf98> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe11430ce48> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe11430ccf8> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe11430cba8> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe11430ca58> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe11430c908> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe11430c7b8> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe11430c668> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe11430c518> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe11430c3c8> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe11430c278> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe11430c128> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe114307f98> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe114307e48> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe114307cf8> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe114307ba8> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe114307a58> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe1143077b8> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe114307668> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe114307518> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe1143073c8> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe114307278> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe114307128> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe114281f98> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe114281e48> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe114281cf8> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe114281ba8> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe114281a58> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n",
      "tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x7fe114281908> exception was never retrieved: Traceback (most recent call last):\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/tornado/gen.py\", line 1069, in run\n",
      "    yielded = self.gen.send(value)\n",
      "  File \"/home/mohsin/anaconda3/lib/python3.6/site-packages/distributed/client.py\", line 1287, in wait\n",
      "    raise AllExit()\n",
      "distributed.client.AllExit\n"
     ]
    }
   ],
   "source": [
    "test = testFeatureGeneration(train, test, cols=['device'], targetcol='is_attributed', func='mean', cname='device_mean')\n",
    "test.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 76,
   "metadata": {},
   "outputs": [
    {
     "ename": "AttributeError",
     "evalue": "'DataFrame' object has no attribute 'to_frame'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-76-2afb79a2000f>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0menc\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mTargetEncoder\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mcols\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m'device'\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mtargetcol\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m'is_attributed'\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mfunc\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m'mean'\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mcname\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m'device_mean'\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0madd_to_orig\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;32mFalse\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 2\u001b[0;31m \u001b[0menc\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mfit\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mX_tr\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mtransform\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mX_val\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;32m~/Kaggle_competitions/Talking_data/Talking_data_codes/TargetEncoderv3.py\u001b[0m in \u001b[0;36mtransform\u001b[0;34m(self, X, y)\u001b[0m\n\u001b[1;32m     68\u001b[0m             \u001b[0mX_transformed\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mX\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mcols\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     69\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 70\u001b[0;31m             \u001b[0mX_transformed\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mX_transformed\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mjoin\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mdictmap\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mto_frame\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mon\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mcols\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mhow\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m'left'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mcname\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     71\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     72\u001b[0m             \u001b[0;32mif\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0madd_to_orig\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/lib/python3.6/site-packages/dask/dataframe/core.py\u001b[0m in \u001b[0;36m__getattr__\u001b[0;34m(self, key)\u001b[0m\n\u001b[1;32m   2311\u001b[0m             return new_dd_object(merge(self.dask, dsk), name,\n\u001b[1;32m   2312\u001b[0m                                  meta, self.divisions)\n\u001b[0;32m-> 2313\u001b[0;31m         \u001b[0;32mraise\u001b[0m \u001b[0mAttributeError\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"'DataFrame' object has no attribute %r\"\u001b[0m \u001b[0;34m%\u001b[0m \u001b[0mkey\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   2314\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   2315\u001b[0m     \u001b[0;32mdef\u001b[0m \u001b[0m__dir__\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mAttributeError\u001b[0m: 'DataFrame' object has no attribute 'to_frame'"
     ]
    }
   ],
   "source": [
    "enc = TargetEncoder(cols=['device'], targetcol=['is_attributed'], func='mean', cname='device_mean', add_to_orig=False)\n",
    "enc.fit(X_tr).transform(X_val)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 73,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "Dask Series Structure:\n",
       "npartitions=1\n",
       "    float64\n",
       "        ...\n",
       "Name: device_mean, dtype: float64\n",
       "Dask Name: rename, 10 tasks"
      ]
     },
     "execution_count": 73,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "tmp = X_tr.groupby(['device'])['is_attributed'].mean()\n",
    "tmp.name = 'device_mean'\n",
    "tmp"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 74,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>device</th>\n",
       "      <th>device_mean</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>20000</th>\n",
       "      <td>1</td>\n",
       "      <td>0.001591</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>20001</th>\n",
       "      <td>1</td>\n",
       "      <td>0.001591</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>20002</th>\n",
       "      <td>1</td>\n",
       "      <td>0.001591</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>20003</th>\n",
       "      <td>1</td>\n",
       "      <td>0.001591</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>20004</th>\n",
       "      <td>1</td>\n",
       "      <td>0.001591</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "       device  device_mean\n",
       "20000       1     0.001591\n",
       "20001       1     0.001591\n",
       "20002       1     0.001591\n",
       "20003       1     0.001591\n",
       "20004       1     0.001591"
      ]
     },
     "execution_count": 74,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "X_val = X_val[['device']].join(tmp.to_frame(), on=['device'])\n",
    "X_val.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 75,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div><strong>Dask DataFrame Structure:</strong></div>\n",
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>device</th>\n",
       "      <th>device_mean</th>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>npartitions=1</th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th></th>\n",
       "      <td>uint16</td>\n",
       "      <td>float64</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th></th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>\n",
       "<div>Dask Name: merge, 14 tasks</div>"
      ],
      "text/plain": [
       "Dask DataFrame Structure:\n",
       "               device device_mean\n",
       "npartitions=1                    \n",
       "               uint16     float64\n",
       "                  ...         ...\n",
       "Dask Name: merge, 14 tasks"
      ]
     },
     "execution_count": 75,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "X_val"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
